import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import Box from '@mui/material/Box';
import CssBaseline from '@mui/material/CssBaseline';
import Stack from '@mui/material/Stack';

import type { Metadata } from 'next';
import { Quicksand } from 'next/font/google';

import { Header, Sidebar } from '@/_components';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = Readonly<{
  children: React.ReactNode;
}>;

const quicksand = Quicksand({
  subsets: ['latin'],
});

const Layout = ({ children }: Props) => (
  <html lang="en" className={quicksand.className}>
    <body>
      <AppRouterCacheProvider>
        <CssBaseline />
        <Header />
        <Stack direction="row">
          <Sidebar>FOO</Sidebar>
          <Box>{children}</Box>
        </Stack>
      </AppRouterCacheProvider>
    </body>
  </html>
);

export default Layout;
