import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import Box from '@mui/material/Box';
import CssBaseline from '@mui/material/CssBaseline';

import type { Metadata } from 'next';
import { Quicksand } from 'next/font/google';

import { Content, Header, Sidebar } from '@/_components';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>;

const quicksand = Quicksand({
  subsets: ['latin'],
});

const Layout = ({ children, modal }: Props) => (
  <html lang="en" className={quicksand.className}>
    <body style={{ height: '100vh', width: '100vw' }}>
      <AppRouterCacheProvider>
        <CssBaseline />
        <Header />
        <Content>
          <Sidebar>FOO</Sidebar>
          <Box sx={{ flexGrow: 1 }}>{children}</Box>
        </Content>
        {modal}
      </AppRouterCacheProvider>
    </body>
  </html>
);

export default Layout;
